config: Disable CONFIG_INFINIBAND_ADDR_TRANS
After enabling more kernel hardening features, this option causes Ubuntu
Bionic builds to fail with the following:

In file included from /<<PKGBUILDDIR>>/include/linux/bitmap.h:9:0,
                 from /<<PKGBUILDDIR>>/include/linux/cpumask.h:12,
                 from /<<PKGBUILDDIR>>/include/linux/smp.h:13,
                 from /<<PKGBUILDDIR>>/include/linux/lockdep.h:14,
                 from /<<PKGBUILDDIR>>/include/linux/mutex.h:17,
                 from /<<PKGBUILDDIR>>/drivers/infiniband/core/addr.c:36:
In function ‘memcpy’,
    inlined from ‘rdma_resolve_ip’ at /<<PKGBUILDDIR>>/drivers/infiniband/core/addr.c:685:3,
    inlined from ‘rdma_addr_find_l2_eth_by_grh’ at /<<PKGBUILDDIR>>/drivers/infiniband/core/addr.c:833:6:
/<<PKGBUILDDIR>>/include/linux/string.h:443:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~
In function ‘memcpy’,
    inlined from ‘rdma_resolve_ip’ at /<<PKGBUILDDIR>>/drivers/infiniband/core/addr.c:690:2,
    inlined from ‘rdma_addr_find_l2_eth_by_grh’ at /<<PKGBUILDDIR>>/drivers/infiniband/core/addr.c:833:6:
/<<PKGBUILDDIR>>/include/linux/string.h:443:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
    __read_overflow2();
    ^~~~~~~~~~~~~~~~~~

I don't expect Liquorix users to use Infiniband products, so just turn
it off.