Revert "config: Change ANDROID_BINDER_IPC to module"
Causes the build error below:
ERROR: modpost: "init_ipc_ns" [drivers/android/binder_linux.ko] undefined!
ERROR: modpost: "put_ipc_ns" [drivers/android/binder_linux.ko] undefined!

This reverts commit d4889aab14e14ea0018942badb05c31396621652.